# Generated by Django 5.1.15 on 2026-06-19 03:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="اسم التصنيف")),
                ("slug", models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "تصنيف",
                "verbose_name_plural": "تصنيفات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="العنوان")),
                ("author", models.CharField(max_length=300, verbose_name="المؤلف")),
                (
                    "aliases",
                    models.TextField(
                        blank=True,
                        help_text="أسماء أو تهجئات بديلة مفصولة بفواصل.",
                        verbose_name="أسماء بديلة",
                    ),
                ),
                (
                    "disambiguation",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظة قصيرة للتمييز بين الكتب المتشابهة.",
                        verbose_name="توضيح التباس",
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, max_length=520, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="encyclopedia.category",
                        verbose_name="التصنيف",
                    ),
                ),
            ],
            options={
                "verbose_name": "كتاب",
                "verbose_name_plural": "كتب",
                "ordering": ["title", "author"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(verbose_name="التعليق")),
                ("hidden", models.BooleanField(default=False, verbose_name="مخفي")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ النشر")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعليق",
                "verbose_name_plural": "تعليقات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="encyclopedia.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إعجاب بتعليق",
                "verbose_name_plural": "إعجابات بتعليقات",
            },
        ),
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("publisher", models.CharField(max_length=300, verbose_name="الناشر")),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="سنة النشر",
                    ),
                ),
                (
                    "editor",
                    models.CharField(blank=True, max_length=300, verbose_name="المحقق/المحرر"),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="عدد الصفحات"),
                ),
                ("city", models.CharField(blank=True, max_length=200, verbose_name="مدينة النشر")),
                ("isbn", models.CharField(blank=True, max_length=40, verbose_name="ISBN")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ التقديم"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الاعتماد"),
                ),
                ("rejection_reason", models.TextField(blank=True, verbose_name="سبب الرفض")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_editions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمد من قبل",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editions",
                        to="encyclopedia.book",
                        verbose_name="الكتاب",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_editions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مقدم الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "طبعة",
                "verbose_name_plural": "طبعات",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="encyclopedia.edition",
                verbose_name="الطبعة",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        max_length=20,
                        verbose_name="الحالة القديمة",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        max_length=20,
                        verbose_name="الحالة الجديدة",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="السبب")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="التاريخ")),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المشرف",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="encyclopedia.edition",
                        verbose_name="الطبعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل اعتماد",
                "verbose_name_plural": "سجلات الاعتماد",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="encyclopedia.edition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edition_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إعجاب بطبعة",
                "verbose_name_plural": "إعجابات بالطبعات",
            },
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_book_title_author"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together={("user", "comment")},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "edition")},
        ),
    ]
