# Generated by Django 5.1.15 on 2026-06-19 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الإخفاء"),
        ),
        migrations.AddField(
            model_name="comment",
            name="hidden_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أخفاه",
            ),
        ),
    ]
