# Generated by Django 5.1.15 on 2026-06-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0002_comment_hidden_at_comment_hidden_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="صورة اختيارية للطبعة (JPEG أو PNG أو WebP، بحد أقصى 2 ميجابايت).",
                null=True,
                upload_to="editions/covers/%Y/%m/",
                verbose_name="صورة الغلاف",
            ),
        ),
    ]
