# Generated by Django 5.2.15 on 2026-06-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0003_edition_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvallog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="التاريخ"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ النشر"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="hidden",
            field=models.BooleanField(db_index=True, default=False, verbose_name="مخفي"),
        ),
        migrations.AlterField(
            model_name="edition",
            name="status",
            field=models.CharField(
                choices=[("pending", "قيد المراجعة"), ("approved", "معتمد"), ("rejected", "مرفوض")],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="edition",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ التقديم"
            ),
        ),
    ]
