# Generated by Django 5.2.15 on 2026-06-21 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_alter_approvallog_timestamp_alter_comment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('author', 'مؤلف'), ('editor', 'محرر/محقق'), ('publisher', 'ناشر')], max_length=20, verbose_name='النوع')),
                ('name', models.CharField(max_length=300, verbose_name='الاسم')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_name_records', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد من قبل')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_name_records', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'اسم مرجعي',
                'verbose_name_plural': 'أسماء مرجعية',
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='unique_name_record_kind_name')],
            },
        ),
    ]
