# Generated by Django 5.2.15 on 2026-06-21 04:28

from django.db import migrations


def seed_name_records(apps, schema_editor):
    NameRecord = apps.get_model("encyclopedia", "NameRecord")
    Book = apps.get_model("encyclopedia", "Book")
    Edition = apps.get_model("encyclopedia", "Edition")

    authors = set(Book.objects.values_list("author", flat=True).distinct())
    for name in authors:
        if name:
            NameRecord.objects.get_or_create(
                kind="author",
                name=name,
                defaults={"status": "approved"},
            )

    editors = set(
        Edition.objects.exclude(editor="").values_list("editor", flat=True).distinct()
    )
    for name in editors:
        if name:
            NameRecord.objects.get_or_create(
                kind="editor",
                name=name,
                defaults={"status": "approved"},
            )

    publishers = set(Edition.objects.values_list("publisher", flat=True).distinct())
    for name in publishers:
        if name:
            NameRecord.objects.get_or_create(
                kind="publisher",
                name=name,
                defaults={"status": "approved"},
            )


def reverse_seed(apps, schema_editor):
    NameRecord = apps.get_model("encyclopedia", "NameRecord")
    NameRecord.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0005_namerecord"),
    ]

    operations = [
        migrations.RunPython(seed_name_records, reverse_seed),
    ]
