# Generated by Django 5.2.15 on 2026-06-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_seed_name_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'مؤلفون',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('encyclopedia.namerecord',),
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
            ],
            options={
                'verbose_name': 'محرر/محقق',
                'verbose_name_plural': 'محررون/محققون',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('encyclopedia.namerecord',),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشرون',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('encyclopedia.namerecord',),
        ),
    ]
