# Generated by Django 5.2.15 on 2026-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_author_editor_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='namerecord',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=320, verbose_name='الslug'),
        ),
    ]
