# Generated by Django 5.2.15 on 2026-06-22 08:41

from django.db import migrations


def populate_name_record_slugs(apps, schema_editor):
    NameRecord = apps.get_model("encyclopedia", "NameRecord")
    for record in NameRecord.objects.filter(slug=""):
        record.save()


def reverse_populate_name_record_slugs(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0008_namerecord_slug"),
    ]

    operations = [
        migrations.RunPython(
            populate_name_record_slugs,
            reverse_populate_name_record_slugs,
        ),
    ]
