# Generated by Django 5.2.15 on 2026-06-22 08:42

from django.db import migrations
from django.utils.text import slugify


def populate_name_record_slugs(apps, schema_editor):
    NameRecord = apps.get_model("encyclopedia", "NameRecord")
    for record in NameRecord.objects.filter(slug=""):
        base = slugify(record.name, allow_unicode=True)
        if not base:
            base = "entry"
        record.slug = f"{base}-{record.pk}"
        record.save(update_fields=["slug"])


def reverse_populate_name_record_slugs(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0009_auto_20260622_1141"),
    ]

    operations = [
        migrations.RunPython(
            populate_name_record_slugs,
            reverse_populate_name_record_slugs,
        ),
    ]
