# Generated by Django 5.2.15 on 2026-06-26 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0010_auto_20260622_1142"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Review",
        ),
        migrations.RenameModel(
            old_name="CommentLike",
            new_name="ReviewLike",
        ),
        migrations.RenameField(
            model_name="reviewlike",
            old_name="comment",
            new_name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="encyclopedia.review",
                verbose_name="المراجعة الأب",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(verbose_name="المراجعة"),
        ),
        migrations.AlterField(
            model_name="review",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="encyclopedia.edition",
                verbose_name="الطبعة",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="hidden_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أخفاها",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="reviewlike",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_likes",
                to="encyclopedia.review",
            ),
        ),
        migrations.AlterField(
            model_name="reviewlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "مراجعة",
                "verbose_name_plural": "مراجعات",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewlike",
            options={
                "verbose_name": "إعجاب بمراجعة",
                "verbose_name_plural": "إعجابات بمراجعات",
            },
        ),
    ]
