# Generated by Django 5.2.15 on 2026-06-26 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0011_review_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'محتوى غير لائق'), ('harassment', 'إساءة'), ('offtopic', 'غير ذي صلة'), ('spam', 'رسائل مزعجة / إعلانات'), ('other', 'أخرى')], max_length=20, verbose_name='السبب')),
                ('details', models.TextField(blank=True, verbose_name='تفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='المُبلّغ')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_reports', to=settings.AUTH_USER_MODEL, verbose_name='حلّه')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='encyclopedia.review', verbose_name='المراجعة')),
            ],
            options={
                'verbose_name': 'بلاغ عن مراجعة',
                'verbose_name_plural': 'بلاغات عن المراجعات',
                'ordering': ['-created_at'],
                'unique_together': {('review', 'reporter')},
            },
        ),
    ]
