# Generated by Django 5.1.15 on 2026-06-27 22:14

from django.db import migrations, models


def backfill_review_depth(apps, schema_editor):
    Review = apps.get_model("encyclopedia", "Review")
    rows = Review.objects.values_list("pk", "parent_id")
    parent_map = dict(rows)
    depth_cache = {}

    def compute_depth(pk):
        if pk in depth_cache:
            return depth_cache[pk]
        chain = []
        current = pk
        while current is not None and current not in depth_cache:
            chain.append(current)
            current = parent_map.get(current)
        base_depth = depth_cache.get(current, 0)
        for idx, node_pk in enumerate(reversed(chain)):
            depth_cache[node_pk] = base_depth + idx + 1
        return depth_cache[pk]

    updates = {}
    for pk in parent_map:
        depth = compute_depth(pk)
        updates.setdefault(depth, []).append(pk)

    for depth, pks in updates.items():
        Review.objects.filter(pk__in=pks).update(depth=depth)


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0012_reviewreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='depth',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='العمق'),
        ),
        migrations.RunPython(backfill_review_depth, migrations.RunPython.noop),
    ]
