# Generated by Django 5.1.15 on 2026-06-28 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_book_categories(apps, schema_editor):
    """Copy the old single category into the new ordered M2M as the primary."""
    Book = apps.get_model("encyclopedia", "Book")
    BookCategory = apps.get_model("encyclopedia", "BookCategory")
    for book in Book.objects.exclude(category_id=None).iterator():
        BookCategory.objects.get_or_create(
            book=book,
            category=book.category,
            defaults={"order": 0},
        )


def reverse_copy_book_categories(apps, schema_editor):
    """Remove all through-model rows created by the forward migration."""
    BookCategory = apps.get_model("encyclopedia", "BookCategory")
    BookCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0013_add_review_depth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 هو التصنيف الرئيسي المستخدم في مسارات التنقل.', verbose_name='الترتيب')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='encyclopedia.book', verbose_name='الكتاب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='encyclopedia.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف كتاب',
                'verbose_name_plural': 'تصنيفات الكتب',
                'ordering': ['book', 'order'],
                'unique_together': {('book', 'category'), ('book', 'order')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', through='encyclopedia.BookCategory', to='encyclopedia.category', verbose_name='التصنيفات'),
        ),
        migrations.RunPython(copy_book_categories, reverse_copy_book_categories),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.CreateModel(
            name='CategorySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف المقترح')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظة المشرف')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_suggestions', to='encyclopedia.book', verbose_name='الكتاب')),
                ('final_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='encyclopedia.category', verbose_name='التصنيف النهائي')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_category_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='عالجه')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الاقتراح')),
            ],
            options={
                'verbose_name': 'اقتراح تصنيف',
                'verbose_name_plural': 'اقتراحات التصنيفات',
                'ordering': ['-created_at'],
            },
        ),
    ]
