# Generated by Django 5.1.15 on 2026-06-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0014_book_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookcategory',
            unique_together={('book', 'category')},
        ),
    ]
