# Generated by Django 5.1.15 on 2026-06-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0016_category_request"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edition",
            old_name="isbn",
            new_name="volumes",
        ),
    ]
