# Generated by Django 5.1.15 on 2026-06-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0017_remove_edition_isbn_edition_volumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="edition",
            name="volumes",
            field=models.CharField(blank=True, max_length=40, verbose_name="المجلدات"),
        ),
    ]
