# Generated by Django 5.1.15 on 2026-06-29 08:10

import django.db.models.deletion
from django.db import migrations, models


def populate_category_paths(apps, schema_editor):
    Category = apps.get_model("encyclopedia", "Category")
    for category in Category.objects.all():
        category.path = f"{category.pk}/"
        category.level = 0
        category.save(update_fields=["path", "level"])


def reverse_populate_category_paths(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0018_review_edited_at_alter_edition_volumes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["path"],
                "verbose_name": "تصنيف",
                "verbose_name_plural": "تصنيفات",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=0, editable=False, verbose_name="المستوى"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="encyclopedia.category",
                verbose_name="التصنيف الأب",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="path",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=500, verbose_name="المسار"
            ),
        ),
        migrations.RunPython(
            populate_category_paths,
            reverse_code=reverse_populate_category_paths,
        ),
    ]
