# Generated by Django 5.1.15 on 2026-06-29 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0019_alter_category_options_category_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Like",
            new_name="EditionVote",
        ),
        migrations.RenameModel(
            old_name="ReviewLike",
            new_name="ReviewVote",
        ),
        migrations.AddField(
            model_name="editionvote",
            name="value",
            field=models.SmallIntegerField(
                choices=[(1, "إعجاب"), (-1, "عدم إعجاب")],
                default=1,
                verbose_name="التصويت",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewvote",
            name="value",
            field=models.SmallIntegerField(
                choices=[(1, "إعجاب"), (-1, "عدم إعجاب")],
                default=1,
                verbose_name="التصويت",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="editionvote",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="encyclopedia.edition",
                verbose_name="الطبعة",
            ),
        ),
        migrations.AlterField(
            model_name="editionvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edition_votes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="encyclopedia.review",
                verbose_name="المراجعة",
            ),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_votes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="editionvote",
            unique_together={("user", "edition")},
        ),
        migrations.AlterUniqueTogether(
            name="reviewvote",
            unique_together={("user", "review")},
        ),
        migrations.AlterModelOptions(
            name="editionvote",
            options={
                "verbose_name": "تصويت بطبعة",
                "verbose_name_plural": "تصويتات بالطبعات",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewvote",
            options={
                "verbose_name": "تصويت بمراجعة",
                "verbose_name_plural": "تصويتات بمراجعات",
            },
        ),
    ]
