# Generated by Django 5.1.15 on 2026-07-01 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_creators(apps, schema_editor):
    """Move existing single-name fields into the new M2M tables."""
    Book = apps.get_model("encyclopedia", "Book")
    Edition = apps.get_model("encyclopedia", "Edition")
    NameRecord = apps.get_model("encyclopedia", "NameRecord")
    BookAuthor = apps.get_model("encyclopedia", "BookAuthor")
    EditionPublisher = apps.get_model("encyclopedia", "EditionPublisher")
    EditionEditor = apps.get_model("encyclopedia", "EditionEditor")

    def get_or_create_record(kind, name):
        name = name.strip()
        if not name:
            return None
        record, _created = NameRecord.objects.get_or_create(
            kind=kind,
            name=name,
            defaults={"status": "approved"},
        )
        return record

    for book in Book.objects.iterator():
        record = get_or_create_record("author", book.author)
        if record:
            BookAuthor.objects.get_or_create(
                book=book,
                name_record=record,
                defaults={"order": 0},
            )

    for edition in Edition.objects.iterator():
        publisher = get_or_create_record("publisher", edition.publisher)
        if publisher:
            EditionPublisher.objects.get_or_create(
                edition=edition,
                name_record=publisher,
                defaults={"order": 0},
            )
        editor = get_or_create_record("editor", edition.editor)
        if editor:
            EditionEditor.objects.get_or_create(
                edition=edition,
                name_record=editor,
                defaults={"order": 0},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0020_rename_like_editionvote_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"], "verbose_name": "كتاب", "verbose_name_plural": "كتب"},
        ),
        migrations.RemoveConstraint(
            model_name="book",
            name="unique_book_title_author",
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "مؤلف الكتاب",
                "verbose_name_plural": "مؤلفو الكتاب",
                "ordering": ["book", "order"],
            },
        ),
        migrations.CreateModel(
            name="EditionEditor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "محرر الطبعة",
                "verbose_name_plural": "محررو الطبعة",
                "ordering": ["edition", "order"],
            },
        ),
        migrations.CreateModel(
            name="EditionPublisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "ناشر الطبعة",
                "verbose_name_plural": "ناشرو الطبعة",
                "ordering": ["edition", "order"],
            },
        ),
        migrations.AddField(
            model_name="bookauthor",
            name="book",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="book_authors", to="encyclopedia.book", verbose_name="الكتاب"),
        ),
        migrations.AddField(
            model_name="bookauthor",
            name="name_record",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="book_author_links", to="encyclopedia.namerecord", verbose_name="المؤلف"),
        ),
        migrations.AddField(
            model_name="editioneditor",
            name="edition",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="edition_editors", to="encyclopedia.edition", verbose_name="الطبعة"),
        ),
        migrations.AddField(
            model_name="editioneditor",
            name="name_record",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="edition_editor_links", to="encyclopedia.namerecord", verbose_name="المحرر/المحقق"),
        ),
        migrations.AddField(
            model_name="editionpublisher",
            name="edition",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="edition_publishers", to="encyclopedia.edition", verbose_name="الطبعة"),
        ),
        migrations.AddField(
            model_name="editionpublisher",
            name="name_record",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="edition_publisher_links", to="encyclopedia.namerecord", verbose_name="الناشر"),
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="authored_books", through="encyclopedia.BookAuthor", to="encyclopedia.namerecord", verbose_name="المؤلفون"),
        ),
        migrations.AddField(
            model_name="edition",
            name="editors",
            field=models.ManyToManyField(blank=True, related_name="edited_editions", through="encyclopedia.EditionEditor", to="encyclopedia.namerecord", verbose_name="المحققون/المحررون"),
        ),
        migrations.AddField(
            model_name="edition",
            name="publishers",
            field=models.ManyToManyField(related_name="published_editions", through="encyclopedia.EditionPublisher", to="encyclopedia.namerecord", verbose_name="الناشرون"),
        ),
        migrations.AlterUniqueTogether(
            name="bookauthor",
            unique_together={("book", "name_record")},
        ),
        migrations.AlterUniqueTogether(
            name="editioneditor",
            unique_together={("edition", "name_record")},
        ),
        migrations.AlterUniqueTogether(
            name="editionpublisher",
            unique_together={("edition", "name_record")},
        ),
        migrations.RunPython(populate_creators, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="edition",
            name="editor",
        ),
        migrations.RemoveField(
            model_name="edition",
            name="publisher",
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=520, unique=True),
        ),
        migrations.AlterField(
            model_name="editionvote",
            name="edition",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="encyclopedia.edition"),
        ),
        migrations.AlterField(
            model_name="editionvote",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="edition_votes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="editionvote",
            name="value",
            field=models.SmallIntegerField(choices=[(1, "إعجاب"), (-1, "عدم إعجاب")], default=1, verbose_name="التصويت"),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="review",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="encyclopedia.review"),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_votes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="reviewvote",
            name="value",
            field=models.SmallIntegerField(choices=[(1, "إعجاب"), (-1, "عدم إعجاب")], default=1, verbose_name="التصويت"),
        ),
    ]
