# Generated by Django 5.1.15 on 2026-07-09 14:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0021_bookauthor_editioneditor_editionpublisher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('proposed_publishers', models.JSONField(blank=True, default=list, verbose_name='الناشرون المقترحون')),
                ('proposed_editors', models.JSONField(blank=True, default=list, verbose_name='المحققون/المحررون المقترحون')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)], verbose_name='سنة النشر')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='مدينة النشر')),
                ('volumes', models.CharField(blank=True, max_length=40, verbose_name='المجلدات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='editions/covers/%Y/%m/', verbose_name='صورة الغلاف')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظة المشرف')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='encyclopedia.edition', verbose_name='الطبعة')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_edition_edit_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='عالجه')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edition_edit_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الاقتراح')),
            ],
            options={
                'verbose_name': 'اقتراح تعديل طبعة',
                'verbose_name_plural': 'اقتراحات تعديل الطبعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
