# Generated by Django 5.1.15 on 2026-07-11 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_book_context(apps, schema_editor):
    EditionVote = apps.get_model("encyclopedia", "EditionVote")
    for vote in EditionVote.objects.filter(book_context__isnull=True).select_related("edition"):
        vote.book_context_id = vote.edition.book_id
        vote.save(update_fields=["book_context"])


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0022_editioneditsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionBookLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('commentary', 'شرح أو حاشية'), ('anthology', 'مجموعة')], default='commentary', max_length=20, verbose_name='العلاقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ربط طبعة بكتاب',
                'verbose_name_plural': 'روابط الطبعات بالكتب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditionBookLinkSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('commentary', 'شرح أو حاشية'), ('anthology', 'مجموعة')], default='commentary', max_length=20, verbose_name='العلاقة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظة المشرف')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
            ],
            options={
                'verbose_name': 'اقتراح ربط طبعة بكتاب',
                'verbose_name_plural': 'اقتراحات ربط الطبعات بالكتب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='editionvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='editionvote',
            name='book_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_votes', to='encyclopedia.book', verbose_name='سياق التصويت'),
        ),
        migrations.RunPython(
            code=set_default_book_context,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='editionvote',
            name='book_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_votes', to='encyclopedia.book', verbose_name='سياق التصويت'),
        ),
        migrations.AlterField(
            model_name='editionvote',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='encyclopedia.edition', verbose_name='الطبعة'),
        ),
        migrations.AlterField(
            model_name='editionvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_votes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterUniqueTogether(
            name='editionvote',
            unique_together={('user', 'edition', 'book_context')},
        ),
        migrations.AddIndex(
            model_name='editionvote',
            index=models.Index(fields=['edition', 'book_context'], name='encyclopedi_edition_918b3d_idx'),
        ),
        migrations.AddField(
            model_name='editionbooklink',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_links', to='encyclopedia.book', verbose_name='الكتاب'),
        ),
        migrations.AddField(
            model_name='editionbooklink',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_links', to='encyclopedia.edition', verbose_name='الطبعة'),
        ),
        migrations.AddField(
            model_name='editionbooklinksuggestion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_link_suggestions', to='encyclopedia.book', verbose_name='الكتاب'),
        ),
        migrations.AddField(
            model_name='editionbooklinksuggestion',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_link_suggestions', to='encyclopedia.edition', verbose_name='الطبعة'),
        ),
        migrations.AddField(
            model_name='editionbooklinksuggestion',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_book_link_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='عالجه'),
        ),
        migrations.AddField(
            model_name='editionbooklinksuggestion',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_link_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الاقتراح'),
        ),
        migrations.AddIndex(
            model_name='editionbooklink',
            index=models.Index(fields=['book', 'role'], name='encyclopedi_book_id_a5adce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='editionbooklink',
            unique_together={('edition', 'book')},
        ),
        migrations.AddConstraint(
            model_name='editionbooklinksuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('edition', 'book', 'suggested_by'), name='unique_pending_book_link_suggestion_per_user'),
        ),
    ]
