# Generated by Django 5.1.15 on 2026-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0023_editionbooklink_editionbooklinksuggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionbooklinksuggestion',
            name='reason',
            field=models.TextField(blank=True, verbose_name='السبب'),
        ),
    ]
