# Generated by Django 5.1.15 on 2026-07-11 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0024_editionbooklinksuggestion_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photocopy', 'طبعة مصورة'), ('reprint', 'إعادة طبع')], default='photocopy', max_length=20, verbose_name='نوع العلاقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_targets', to='encyclopedia.edition', verbose_name='الطبعة الأصل')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sources', to='encyclopedia.edition', verbose_name='الطبعة المرتبطة')),
            ],
            options={
                'verbose_name': 'علاقة بين طبعتين',
                'verbose_name_plural': 'علاقات بين الطبعات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'kind'], name='encyclopedi_source__8046be_idx'), models.Index(fields=['target', 'kind'], name='encyclopedi_target__1d7a81_idx')],
                'unique_together': {('source', 'target', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='EditionRelationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photocopy', 'طبعة مصورة'), ('reprint', 'إعادة طبع')], default='photocopy', max_length=20, verbose_name='نوع العلاقة')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظة المشرف')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_edition_relation_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='عالجه')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_suggestions', to='encyclopedia.edition', verbose_name='الطبعة الأصل')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edition_relation_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الاقتراح')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relation_suggestions', to='encyclopedia.edition', verbose_name='الطبعة المرتبطة')),
            ],
            options={
                'verbose_name': 'اقتراح علاقة بين طبعتين',
                'verbose_name_plural': 'اقتراحات علاقات بين الطبعات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('source', 'target', 'kind', 'suggested_by'), name='unique_pending_edition_relation_suggestion_per_user')],
            },
        ),
    ]
