# Generated by Django 5.1.15 on 2026-07-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0025_edition_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionrelationsuggestion',
            name='target_data',
            field=models.JSONField(blank=True, default=dict, help_text='تُستخدم عند اقتراح طبعة غير موجودة بعد.', verbose_name='بيانات الطبعة الجديدة'),
        ),
        migrations.AlterField(
            model_name='editionrelationsuggestion',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_relation_suggestions', to='encyclopedia.edition', verbose_name='الطبعة المرتبطة'),
        ),
    ]
