# Generated by Django 5.1.15 on 2026-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0026_editionrelationsuggestion_target_data_and_more'),
    ]

    operations = [
        # Backfill existing editions as "best" so current expert badges stay.
        migrations.AddField(
            model_name='edition',
            name='is_best',
            field=models.BooleanField(default=True, help_text="إذا كنت خبيراً واخترت هذا الخيار، سيظهر ختم 'رشحها خبير' على الطبعة.", verbose_name='هل هذه أفضل طبعة؟'),
        ),
        # New submissions should default to unchecked.
        migrations.AlterField(
            model_name='edition',
            name='is_best',
            field=models.BooleanField(default=False, help_text="إذا كنت خبيراً واخترت هذا الخيار، سيظهر ختم 'رشحها خبير' على الطبعة.", verbose_name='هل هذه أفضل طبعة؟'),
        ),
    ]
