# Generated by Django 5.1.15 on 2026-07-14 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_self_likes_for_pending_suggestions(apps, schema_editor):
    CategorySuggestion = apps.get_model("encyclopedia", "CategorySuggestion")
    CategorySuggestionVote = apps.get_model("encyclopedia", "CategorySuggestionVote")
    for suggestion in CategorySuggestion.objects.filter(
        status="pending", suggested_by__isnull=False
    ):
        CategorySuggestionVote.objects.get_or_create(
            suggestion=suggestion,
            user=suggestion.suggested_by,
            defaults={"value": 1},
        )


def remove_auto_self_likes(apps, schema_editor):
    CategorySuggestionVote = apps.get_model("encyclopedia", "CategorySuggestionVote")
    CategorySuggestionVote.objects.filter(
        value=1,
        user=models.F("suggestion__suggested_by"),
        suggestion__status="pending",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0029_populate_namerecord_slugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorysuggestion",
            name="status",
            field=models.CharField(
                choices=[("pending", "غير مُتحقَّق"), ("approved", "معتمد"), ("rejected", "مرفوض")],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.CreateModel(
            name="CategorySuggestionVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(1, "إعجاب"), (-1, "عدم إعجاب")], default=1, verbose_name="التصويت"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="encyclopedia.categorysuggestion",
                        verbose_name="اقتراح التصنيف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_suggestion_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصويت على اقتراح تصنيف",
                "verbose_name_plural": "تصويتات على اقتراحات التصنيفات",
                "indexes": [
                    models.Index(fields=["suggestion"], name="encyclopedi_suggest_1502e5_idx")
                ],
                "unique_together": {("user", "suggestion")},
            },
        ),
        migrations.RunPython(
            create_self_likes_for_pending_suggestions,
            reverse_code=remove_auto_self_likes,
        ),
    ]
