# Generated by Django 5.1.15 on 2026-07-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0030_category_suggestion_votes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="editioneditor",
            options={
                "ordering": ["edition", "order"],
                "verbose_name": "محقق الطبعة",
                "verbose_name_plural": "محققو الطبعة",
            },
        ),
        migrations.AlterModelOptions(
            name="editor",
            options={"ordering": ["name"], "verbose_name": "محقق", "verbose_name_plural": "محققون"},
        ),
        migrations.AlterField(
            model_name="edition",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="edited_editions",
                through="encyclopedia.EditionEditor",
                to="encyclopedia.namerecord",
                verbose_name="المحققون",
            ),
        ),
        migrations.AlterField(
            model_name="editioneditor",
            name="name_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edition_editor_links",
                to="encyclopedia.namerecord",
                verbose_name="المحقق",
            ),
        ),
        migrations.AlterField(
            model_name="editioneditsuggestion",
            name="proposed_editors",
            field=models.JSONField(blank=True, default=list, verbose_name="المحققون المقترحون"),
        ),
        migrations.AlterField(
            model_name="namerecord",
            name="kind",
            field=models.CharField(
                choices=[("author", "مؤلف"), ("editor", "محقق"), ("publisher", "ناشر")],
                max_length=20,
                verbose_name="النوع",
            ),
        ),
    ]
