# Generated by Django 5.1.15 on 2026-07-15 11:49

from django.db import migrations, models


def clear_dummy_cities(apps, schema_editor):
    """Discard per-edition city values now that city is linked to publishers."""
    Edition = apps.get_model("encyclopedia", "Edition")
    EditionEditSuggestion = apps.get_model("encyclopedia", "EditionEditSuggestion")
    Edition.objects.exclude(city="").update(city="")
    EditionEditSuggestion.objects.exclude(city="").update(city="")


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0031_alter_editioneditor_options_alter_editor_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="namerecord",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="مدينة نشر يدوية (اختيارية؛ تُستخدم عند وجود أكثر من ناشر).",
                max_length=200,
                verbose_name="مدينة النشر",
            ),
        ),
        migrations.AlterField(
            model_name="edition",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="مدينة نشر يدوية (اختيارية؛ تُستخدم عند وجود أكثر من ناشر).",
                max_length=200,
                verbose_name="مدينة النشر",
            ),
        ),
        migrations.AlterField(
            model_name="editioneditsuggestion",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="مدينة نشر يدوية (اختيارية؛ تُستخدم عند وجود أكثر من ناشر).",
                max_length=200,
                verbose_name="مدينة النشر",
            ),
        ),
        migrations.RunPython(clear_dummy_cities, migrations.RunPython.noop),
    ]
