# Generated by Django 5.1.15 on 2026-07-16 13:35

import uuid

from django.db import migrations, models


def _generate_edition_public_ids(apps, schema_editor):
    Edition = apps.get_model("encyclopedia", "Edition")
    for edition in Edition.objects.all():
        if not edition.public_id:
            edition.public_id = uuid.uuid4()
            edition.save(update_fields=["public_id"])
        # SQLite with bulk updates can reuse callable defaults; force unique if needed.
        while Edition.objects.exclude(pk=edition.pk).filter(public_id=edition.public_id).exists():
            edition.public_id = uuid.uuid4()
            edition.save(update_fields=["public_id"])


def _generate_review_public_ids(apps, schema_editor):
    Review = apps.get_model("encyclopedia", "Review")
    for review in Review.objects.all():
        if not review.public_id:
            review.public_id = uuid.uuid4()
            review.save(update_fields=["public_id"])
        while Review.objects.exclude(pk=review.pk).filter(public_id=review.public_id).exists():
            review.public_id = uuid.uuid4()
            review.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0032_namerecord_city_alter_edition_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.RunPython(
            _generate_edition_public_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            _generate_review_public_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="edition",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
