# Generated by Django 5.1.15 on 2026-06-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="magic_link_nonce",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Single-use nonce for magic-link login.",
                max_length=64,
            ),
        ),
    ]
