# Generated by Django 5.2.15 on 2026-06-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_magic_link_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expert_flair',
            field=models.CharField(blank=True, default='', help_text="النص الذي يظهر بجانب اسم المستخدم الخبير. إذا ترك فارغاً، ستظهر 'خبير'.", max_length=50, verbose_name='شارة الخبير'),
        ),
    ]
