# Generated by Django 5.1.15 on 2026-06-28 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


def reverse_create_missing_profiles(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_expert_flair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='اختيارية. JPEG أو PNG أو WebP، بحد أقصى 2 ميجابايت.', null=True, upload_to='avatars/%Y/%m/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='الموقع')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('twitter_x', models.URLField(blank=True, verbose_name='رابط X / Twitter')),
                ('telegram', models.URLField(blank=True, verbose_name='رابط Telegram')),
                ('facebook', models.URLField(blank=True, verbose_name='رابط Facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='رابط LinkedIn')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'ملفات شخصية',
            },
        ),
        migrations.RunPython(create_missing_profiles, reverse_create_missing_profiles),
    ]
